services:
  chrome:
    container_name: "chrome"
    image: "selenium/standalone-chrome:108.0-chromedriver-108.0"
    shm_size: "2gb"
    ports:
      - "${VNCPORT:-127.0.0.1:7900}:7900"
    environment:
      - SE_SCREEN_WIDTH=1040
      - SE_SCREEN_HEIGHT=840
      - SE_SCREEN_DEPTH=24
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chrome:4444/"]
      interval: 5s
      retries: 5
      start_period: 5s

  devtest:
    container_name: "devtest"
    image: "golang:1.24rc2-alpine3.20"
    #tty: true
    #stdin_open: true
    user: "${USERID:-1000}"
    working_dir: "/home/user/src/c2FmZQ/c2FmZQ"
    command: "go test -v -failfast -tags selenium -timeout=15m -run=${TESTS:-.*} ./internal/pwatests/..."
    environment:
     - HOME=/home/user
     - GOPATH=/home/user/go
     - GOCACHE=/home/user/.cache/go-build
     - CGO_ENABLED=0
    volumes:
      - "${GOCACHE:-$HOME/.cache/go-build}:/home/user/.cache/go-build"
      - "${GOPATH:-$HOME/go}:/home/user/go"
      - "${SRCDIR:-$HOME/src/c2FmZQ}:/home/user/src/c2FmZQ"
    depends_on:
      chrome:
        condition: service_healthy
